README.md, tfreader/LICENSE, tfreader/pyproject.toml, tfreader/tfreader.py
We are using the [Flit Python package](https://flit.readthedocs.io/en/latest/) to facilitate publication to the [Python Package Index (PyPI)](https://pypi.org/).  These changes enable the `flit publish` command to succeed.
=> ENH: Modifications for flit

tensorflow_reader/tensorflow_reader.py
This constructs the input dataset using tensorflow graph constructs.  In theory, this allows tensorflow to optimize the order of the steps so as to maximize performance.  However, it is about 4 times slower than the implementation that it replaces.  I am putting it here for soliciting feedback, and in case it proves useful in the future to have this documented.  
**See comments below as to why this is now a pull request that can be merged.**
=> ENH: construct dataset using tensorflow graph

superpixel.ipynb
This is adapted from a version by @cooperlab.
This code compares three implementations of the SLIC algorithm for computing superpixels from an image.  The `skimage` and `Simple ITK` versions produce reasonable results; the `fast_slic` version is not producing reasonable results.  By default, this code is running on an 8 × 8 tiling of an image of an astronaut.  Set it to 1 × 2 or 2 × 2 to see more detail.
The runtime for `skimage` is 3.7 seconds, for `Simple ITK` is 0.46 seconds, and for `fast_slic` is 0.10 seconds.  Because the output of the last is suspicious, these timings support the use of `Simple ITK`, though further investigation to the quality of the superpixel construction is warranted.
=> ENH: Add superpixel jupyter notebook

tensorflow_reader/pyproject.toml
Add the list of runtime dependencies to the configuration file for Flit so that they are known to PyPI and pip.  Closes #22.
=> ENH: Name runtime dependencies

Zarr Size Comparison.ipynb, tensorflow_reader/tensorflow_reader.py, wsi_reader.ipynb
A mask file can be supplied to determine which tiles from a whole slide image should be retained for learning or inference.  This mask is first [resampled](https://itk.org/ITKExamples/src/Filtering/ImageGrid/ResampleAnImage/Documentation.html) if necessary so that it has exactly one pixel for each and every tile that could be selected for subsequent processing.  A non-zero value for a pixel indicates that the corresponding tile should be kept.
Also,
ENH: Stop using zarr-jpeg package, which is problematic in our context
STYLE: Use snake_case for Python function and variable names
=> ENH: TensorFlow graph handles tile-selection mask

tensorflow_reader/tensorflow_reader.py, wsi_reader.ipynb
Patch to do mask resampling (from supplied size (in pixels) to one pixel per tile) via tensorflow rather than via ITK.
=> ENH: Implement mask resampling via tensorflow

tensorflow_reader/tensorflow_reader.py, wsi_reader.ipynb
Instead of supplying lambda expressions or other functions as the first parameter to `tensorflow.dataset.map()` calls, we now supply callable classes.  For each callable class, this makes initialization code be encapsulated in the `__init__` method and the actual dataset manipulation be encapsulated in the `__call__` method.  Subroutines of these methods are encapsulated as private methods of the callable classes.
The steps of a function implementing a pipeline are now much simpler and more compact.  They require two basic operations, construction of the callable class and supplying the callable class to the `tensorflow.dataset.map()` function.  An entire pipeline might now fit on a single page because the parts that should be internal to any given pipeline step now are internal.
=> ENH: New architecture: supply callable classes to tf.dataset.map()

.git-blame-ignore-revs, .github/workflows/build-test-package.yml, setup.py
ENH: Removing tensorflow as a required dependency from setup.py because the user will likely wish to specify the specific version for compatibility with the installed CUDA libraries, etc.  Installing (current version of) tensorflow via GitHub action.
Also,
BUG: Fix .git-blame-ignore-revs entry.
=> ENH: Cuda compatibility

histomics_stream/dsm/chunk.py, histomics_stream/dsm/wsi.py
Support that some slides will have masks and others might not, by allowing the empty string, "", as the name of a mask file when no mask file is to be supplied.
=> ENH: Handle mask_filename=="".

.github/workflows/build-test-package.yml, README.md, histomics_stream/__init__.py, histomics_stream/configure.py, histomics_stream/tensorflow.py, setup.py
=> ENH: Use large_image to read whole slide image.

histomics_stream/tensorflow.py
Although it is not documented, if it is a tensorflow dataset then the first parameter of `tensorflow.model.predict` can cause something screwy to happen.  I am not 100% sure about this, but it appears that such a first parameter is treated as is the first parameter of `tensorflow.model.fit`.  In particular, if that first parameter is a tuple of length 2 or 3 then it is interpreted as the same length prefix of `(inputs, targets, sample_weights)`.  The previous return value from a callable `histomics_stream.CreateTensorFlowDataset` instance was of the form `(rgb_pixel_values, dictionary_of_annotations)` and the second argument was being misinterpreted as `targets`.  With this pull request, calling an instance of `CreateTensorFlowDataset` instead returns each tensorflow dataset element as …
=> ENH: Dataset element is now ((rgb, annotations), None, None).

README.md, example/tensorflow_stream.ipynb, histomics_stream/__init__.py, setup.py
Bump version to 2.1.3.
Install `python3-openslide`.
Add `tensorflow>=2.6.0,<2.7` dependency.
Add advice that Google Colab may require `Runtime->Restart runtime`.
Add GitHub badge to README.md.
This works in docker and in Python virtual environments, etc, but does not work on Google Colab unless the user selects `Runtime->Restart runtime` after installing the `large_image package`.  A change to `large_image` to work around this is in the works.
=> ENH: Notebook now runs on Google Colab.

histomics_stream/__init__.py, histomics_stream/tensorflow.py, setup.py
Tensorflow complains of `tf.float64` vs. `tf.float32` incompatibility in some scenarios.  With this pull request, we are casting everything relevant to `tf.float64`.
=> Fix mismatched float problem

example/tensorflow_stream.ipynb, histomics_stream/configure.py
ENH: Allow specification of mask_threshold.
ENH: Updated tensorflow_stream.ipynb jupyter lab.
The physical area of a tile on a whole slide image may overlap the physical area of multiple pixels in the mask.  The tile is retained if the fraction of its area that is physically represented by non-zero mask pixels is greater than the specified mask_threshold.  Additionally a bug where overlapping tiles were not properly aligned with the mask has been fixed.
=> BUG: Better alignment accuracy between overlapping tiles and mask.

example/tensorflow_stream.ipynb, histomics_stream/__init__.py, histomics_stream/configure.py, histomics_stream/tensorflow.py, setup.py
Can set `magnification_source` to `scan`, `native` or `exact`.  `scan` returns the highest magnification available.   `native` returns the nearest natively available magnification among those that are at least 98% of the requested magnification.  `exact` takes the `native` magnification and resamples it to exactly the requested target magnification.
=> ENH: Support target_magnification and magnification_source parameters.

.github/workflows/build-test-package.yml, histomics_stream/__init__.py, pyproject.toml, setup.py
Modified `.github/workflows/build-test-package.yml` and `pyproject.toml` to enable automatic publishing to PyPITest, and for tagged commits, to PyPI.
=> ENH: Automatically publish to PyPI

histomics_stream/configure.py, histomics_stream/tensorflow.py, test/test_create_tensorflow_dataset.py
Also:
STYLE: black formatting
The `large_image` `getRegion` command was not recognizing `scale=dict(level=level)` but does work with `scale=dict(magnification=returned_magnification)`.
=> BUG: Use magnification rather than level for large_image read

histomics_stream/__init__.py, histomics_stream/configure.py, histomics_stream/tensorflow.py
Handle not just SVS, but  now all image formats except ZARR, via `large_image`.  Previously `PIL` was handling everything but SVS and ZARR.
=> ENH: Use large_image for NDPI, etc., not just SVS files

example/tensorflow_stream.ipynb, histomics_stream/__init__.py, pyproject.toml
Although they can be useful for other examples, in this example we need only `large_image[openslide]`, not the full `large_image[openslide,ometiff,openjpeg,bioformats]`.
Also, `histomics_stream` does not need the direct python dependency `openslide-python` because the needed functionality is installed in via `large_image[openslide]`.
=> Large image

README.md, StudyObject.md
Add `StudyObject.md` file to describe the hierarchical Python `dict` object that is used to describe a study, its slides, and their chunks and tiles.
=> DOC: Describe the Python `study` dict

example/tensorflow_stream.ipynb
Improve the `tensorflow_stream.ipynb` jupyter lab.  Specifically,
- Store notebook cells' outputs in the file.
- Separate installation of `histomics_stream` and its dependencies from the installation of other packages that happen to be used in the notebook, including installing `itkwidgets` to Python and `jupyter labextension`.
- Take a single element from `tiles` tensorflow `Dataset` and show its parts, including using `itkwidgets` to show the tile's RGB image.
=> DOC: Show internals, image in tensorflow_stream.ipynb

StudyObject.md
Add more information about `slide["chunks"]`.
=> DOC: Explain keys of `chunks` dictionary

example/tensorflow_stream.ipynb
Google Colab complains that it cannot find `cudnn` when the TensorFlow model is instantiated.  I suspect that this is a versioning issue; maybe the default installed `cudnn` is not compatible with the latest version of `tensorflow-gpu` (which is currently 2.8.0).  Installing the latest `libcudnn8` and `libcudnn8-dev` fixes the problem.
=> ENH: Explicitly apt install libcudnn8 libcudnn8-dev

histomics_stream/configure.py, histomics_stream/tensorflow.py
This includes several bundled performance improvements:
PERF: Use N log N approach for collating tiles into chunks instead of N^2
PERF: Use `large_image_source_tiff` to read a chunk from disk instead of `large_image`
PERF: More efficiently create input to `tf.data.Dataset.from_tensor_slices` rather than from multiple `dataset` objects
PERF: Support `num_workers` and `worker_index` for sharding in `CreateTensorFlowDataset`
PERF: Make `_py_read_chunk` be `@staticmethod`
The collating of tiles into chunks takes 14s instead of 175s on the example I tested with.
I don't see anything controversial here and will merge it in 24 hours if I hear no objections.
=> PERF: Memory and runtime improvements

.github/workflows/build-test-package.yml, histomics_stream/configure.py, test/test_find_imports.py, test/test_mask.py
Also, don't be as explicit with GitHub about directly installing dependencies.  Instead, let GitHub's invocation of `pip install histomics_stream` install those dependencies by referring to `pyproject.toml`.
=> TEST: Add test for mask, imports

histomics_stream/configure.py
Don't assume that the slide file will be a format recognized by `large_image_source_tiff`.
=> ENH: Check file name suffix for large_image_source_tiff

histomics_stream/configure.py
@Leengit This is an odd issue I came across with more details [here](https://stackoverflow.com/questions/37726830/how-to-determine-if-a-number-is-any-type-of-int-core-or-numpy-signed-or-not).
Should I apply this to other `isinstance(x, int)` checks with user-provided values too? Numpy types will be common.
=> Use (int, np.integer) in isinstance

histomics_stream/configure.py
Where we check for
```python
isinstance(my_variable, int)
```
instead also allow `numpy.integer`
```python
isinstance(my_variable, (int, np.integer))
```
Similarly allow `numpy.floating` when `float` is the checked type.
Closes #125.
=> BUG: Allow types np.integer and np.floating

histomics_stream/configure.py
When `large_image` is asked to return tiles with an `"exact"` magnification it may end up using a `level` (in the sense that `large_image` defines it) that is a non-integer.  (Also, a non-integer value of `level` might occur if the stored `"native"` magnifications are different by something other than powers of two.)  However, if that level is within `1e-6` of an integer we will return it as type `int` rather than type `float`.
@cooperlab if it would be better to round to the integer value but leave it as type `float`, please let me know.
Closes #95.
=> ENH: Return `level` as type `int` if it is very close to an integer

example/performance-EfficientNetV2S.py, example/performance-EfficientNet_V2_S_Weights.IMAGENET1K_V1.py, example/performance-detection.py, example/performance-mnist.py, histomics_stream/pytorch.py, histomics_stream/tensorflow.py, pyproject.toml
Starts the work towards satisfying #102 by implementing 4 performance scripts.  These are a start, but further work will be needed.
Also, towards the performance goals, explores ways to incorporate multiple workers / multiple process into the `torch` `Dataset` and `DataLoader`.  The `predict_and_detach` function proved essential to stop `torch` from crashing with too may un-detached tensors.  Other approaches were of less use, were ultimately culled, but are left as intermediate git commits to document what was researched.  (For example, `DataLoader`s stalled inexplicably when iterated within a `torch.multiprocessing.Process`.)  The final commit indicates future directions for this aspect.
=> TEST: Add scripts for performance profiling

histomics_stream/configure.py
When interacting with slide metadata in configure.py, try to use tiff tile source first then fall back to openslide if that fails. The openslide tile source may be leaking.
=> issue 131 try to use tiff source first

example/performance-EfficientNetV2S.py, example/performance-EfficientNet_V2_S_Weights.IMAGENET1K_V1.py, example/performance-detection.py, example/performance-mnist.py, histomics_stream/codecs.py, histomics_stream/configure.py, histomics_stream/pytorch.py, histomics_stream/tensorflow.py
Arrange the order of Python `import` statements with `isort` and then format them with `black -C`.
=> Arrange imports with `isort`

.github/workflows/build-test-package.yml, README.md, example/pytorch_stream.ipynb, example/tensorflow_stream.ipynb, histomics_stream/configure.py, pyproject.toml, test/test_mask.py
=> ENH: Make tensorflow,torch,zarr packages optional

.github/dependabot.yml, .github/workflows/build-test-package.yml
GitHub gave errors about publishing HistomicsStream `2.5.0`.  I am hoping that bumping `actions/setup-python@v1` to `actions/setup-python@v2` in `.github/workflows/build-test-package.yml` will be sufficient to fix the problem, but I don't know how to test that other than merging this pull request and attempting to make a `2.5.1` release via GitHub.
=> COMP: Update GitHub actions for publishing to PyPI

.github/workflows/build-test-package.yml
An error reply from GitHub actions suggests that these permissions be added.
=> COMP: Give GitHub actions "id-token: write" permissions
